baseURL = "https://poro.com.ar"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify3"
title = "Poro"

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="Poro"
description = "Poro"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

  [params.commentEngine]
  code = """
  """

  [params.sharingbuttons]
  facebook = true
  twitter = true
  email = true
  linkedin = true
  reddit = true
  whatsapp = true
  hackernews = false
  telegram = false
